CREATE TABLE delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_code VARCHAR(20) NOT NULL UNIQUE,
    recipient VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    delivered_at TIMESTAMP,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_delivery_status
        CHECK (status IN ('CREATED', 'IN_TRANSIT', 'DELIVERED', 'CANCELED'))
);
