CREATE TABLE delivery_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id BIGINT NOT NULL,
    previous_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_delivery_status_history_delivery
        FOREIGN KEY (delivery_id) REFERENCES delivery(id) ON DELETE CASCADE,
    CONSTRAINT chk_delivery_status_history_previous_status
        CHECK (previous_status IS NULL OR previous_status IN ('CREATED', 'IN_TRANSIT', 'DELIVERED', 'CANCELED')),
    CONSTRAINT chk_delivery_status_history_new_status
        CHECK (new_status IN ('CREATED', 'IN_TRANSIT', 'DELIVERED', 'CANCELED'))
);

CREATE INDEX idx_delivery_status_history_delivery_changed_at
    ON delivery_status_history (delivery_id, changed_at);

INSERT INTO delivery_status_history (delivery_id, previous_status, new_status, changed_at)
SELECT id, NULL, status, COALESCE(update_at, create_at)
FROM delivery;
